### ISSUE TITLE
Intuition about grouped/depthwise convolution

### ISSUE THREAD

**Issue by minh-nguyenhoang** [StarostinV/convkan#1]
After reading about KAN and its implementation today, I have tried to implement the KAN layer with convolution. That's when I stumble on your repo. Your repo's implementation is really thorough and easy to read, but still there is this thing that always weird me out about the grouped/depthwise convolution case, and I see that your repo may make a mistake when it come to grouped/depthwise convolution, as if you see my implementation of the normal grouped/depthwise convolution below:
```
import torch
import torch.nn.functional as F

def _ntuple( n ):
    def parse(x):
        import collections.abc
        from itertools import repeat
        if isinstance(x, collections.abc.Iterable) and not isinstance(x, str):
            return tuple(x)
        return tuple(repeat(x, n))
    return parse

def _pair(x):
    return _ntuple(2)(x)

def conv2d_matmul(input: torch.Tensor, weight: torch.Tensor, bias: None | torch.Tensor = None, stride=1, padding=0, dilation=1, groups=1):
    padding, stride, dilation = _pair(padding), _pair(stride), _pair(dilation)
    bsz, channels, h, w = input.shape
    out_channels, in_channels, k_h, k_w = weight.shape

    assert channels == in_channels*groups, 'Number of input channels and kernel channels must match'

    inp_unfold = F.unfold(input, weight.shape[-2: ], dilation=dilation, padding=padding, stride=stride)
    bsz, channels_and_elem, n_patches = inp_unfold.shape

    inp_flatten = inp_unfold.permute(0,2,1).reshape(bsz * n_patches, groups, channels_and_elem // groups).permute(1,0,2) # [groups, B*H_out*W_out, elems (in_features)]
    weight_flatten = weight.view( groups, out_channels // groups,  -1).permute(0,2,1) #[groups, elems (in_features), out_features (out_channels// groups)]
    
    out = torch.bmm(inp_flatten, weight_flatten).permute(1,0,2).reshape(bsz, n_patches, -1).permute(0,2,1)
    if bias is not None:
        out += bias.view(1,-1,1)
    h_out = int((h + padding[0]*2 - dilation[0]*(k_h-1) - 1)/stride[0]) + 1
    w_out = int((w + padding[1]*2 - dilation[1]*(k_w-1) - 1)/stride[1]) + 1

    out = out.view(bsz, out_channels, h_out,w_out)
    return out
```
As you can see, in the normal convolution, the number of weight matrices is proportional to the number of groups (with shape `[groups, elems (in_features), out_features (out_channels// groups)]`, but your implementation will just be equal to the weight matrix with shape `[elems (in_features), out_features (out_channels// groups)]`.

**Comment by minh-nguyenhoang** [comment]
[conv_kan.txt](https://github.com/StarostinV/convkan/files/15277205/conv_kan.txt)
[conv_normal.txt](https://github.com/StarostinV/convkan/files/15277206/conv_normal.txt)
[linear_kan.txt](https://github.com/StarostinV/convkan/files/15277207/linear_kan.txt)

As I am too lazy to create a PR, I would leave the modified version of conv_kan and linear_kan that supports grouped convolution KAN that actually do what grouped convolution should do. You can use this to correct the code

**Comment by StarostinV** [comment]
Spot on! My implementation basically applied the same kernels (splines) to every group, but making separate kernels would either require initializing multiple KANLinear layers or modifying KANLinear (as you have done). Your code makes sense and passes the tests, so I will push it soon. Thank you!
