### ISSUE TITLE
Tring to do padding_mode = 'same'

### ISSUE THREAD

**Issue by maayange17** [StarostinV/convkan#3]
When trying to do padding mode = 'same'
I get the next error:
![image](https://github.com/StarostinV/convkan/assets/47349086/aff4c502-4fc9-48ef-bcb5-5f7d637f77de)

Can you add this mode to the code?

**Comment by StarostinV** [comment]
Thanks for pointing this out, I will implement "same" and "valid" paddings soon.

**Comment by StarostinV** [comment]
Added support for "same" and "valid" padding #7
